In [15]:
import numpy as np
import random
stock_prices = np.random.randint(100, 500, (2,5))
print(stock_prices)
print("Average stock_prices: ",np.mean(stock_prices, axis=0))
m = np.max(stock_prices)
x = np.unravel_index(np.argmax(stock_prices),stock_prices.shape)
print("Highest price recorded: ",m," at Day ",x[1]+1,", Company ",x[0]+1)
# print((stock_prices-np.min(stock_prices)/(np.max(stock_prices)-np.min(stock_prices))))
d = np.diff(stock_prices, axis=1)
print(d)
# print(d[d>0], d[d<200])


[[193 250 349 340 158]
 [478 415 477 251 424]]
Average stock_prices:  [335.5 332.5 413.  295.5 291. ]
Highest price recorded:  478  at Day  1 , Company  2
[[  57   99   -9 -182]
 [ -63   62 -226  173]]


In [18]:
# authorization.py
import re
import json
import logging

logging.basicConfig(level=logging.INFO, format='%(name)s - %(levelname)s - %(message)s')
logging.info("a")

class LaunchAuthorizationSystem:
    """Handles nuclear launch authorization validation."""
    
    # AUTH_PATTERN = r””# Regex for security code validation

    @staticmethod
    def validate_code(code):
        """Validates the launch authorization code."""


INFO:root:a
